# Generated by Django 5.1.5 on 2026-03-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnr_number', models.CharField(max_length=32, unique=True)),
                ('case_type', models.CharField(max_length=120)),
                ('court_name', models.CharField(max_length=255)),
                ('petitioner', models.CharField(max_length=255)),
                ('respondent', models.CharField(max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('last_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disposed', 'Disposed'), ('stayed', 'Stayed')], max_length=20)),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('order_pdf_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=120)),
                ('source_reference', models.CharField(max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.caserecord')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(blank=True, max_length=100)),
                ('village_name', models.CharField(max_length=150)),
                ('survey_number', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=255)),
                ('area_hectare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('land_type', models.CharField(max_length=120)),
                ('geojson_boundary', models.JSONField(blank=True, default=dict)),
                ('ror_reference', models.CharField(blank=True, max_length=200)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('state', 'district', 'village_name', 'survey_number', 'owner_name')},
            },
        ),
        migrations.CreateModel(
            name='ParcelCaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_links', to='records.caserecord')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='records.landparcel')),
            ],
            options={
                'unique_together': {('parcel', 'case')},
            },
        ),
    ]
